version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    image: smsai-api:latest
    env_file: .env
    environment:
      - LICENSE_ENFORCE=1
    ports:
      - "8081:8081"
    volumes:
      - ./synapseflow_data:/app/synapseflow_data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  twilio-webhook:
    build:
      context: ./docker/twilio-webhook
      dockerfile: Dockerfile
    image: smsai-twilio:latest
    env_file: .env
    environment:
      - LICENSE_ENFORCE=1
    ports:
      - "5005:5005"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  messenger-webhook:
    build:
      context: ./docker/messenger-webhook
      dockerfile: Dockerfile
    image: smsai-msgr:latest
    env_file: .env
    environment:
      - LICENSE_ENFORCE=1
    ports:
      - "5006:5006"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5006/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
