name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements-test-client.txt
      - name: Run tests
        env:
          LICENSE_ENFORCE: "0"
          OLLAMA_DISABLE: "1"
        run: |
          . .venv/bin/activate
          pytest -q
